In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

In [26]:
apple_complete = pd.read_csv(r"C:/Users/soso/Desktop/AAPL.csv")

In [27]:
apple_complete.head()

Date       Open       High        Low      Close  Adj Close  \
0  2013-01-02  19.779285  19.821428  19.343929  19.608213  16.890797   
1  2013-01-03  19.567142  19.631071  19.321428  19.360714  16.677595   
2  2013-01-04  19.177500  19.236786  18.779642  18.821428  16.213051   
3  2013-01-07  18.642857  18.903570  18.400000  18.710714  16.117674   
4  2013-01-08  18.900356  18.996071  18.616072  18.761070  16.161053   

      Volume  
0  560518000  
1  352965200  
2  594333600  
3  484156400  
4  458707200

In [28]:
df = apple_complete.iloc[:,0:2]
df.head()

Date       Open
0  2013-01-02  19.779285
1  2013-01-03  19.567142
2  2013-01-04  19.177500
3  2013-01-07  18.642857
4  2013-01-08  18.900356

In [6]:
df.isnull().any()

Date    False
Open    False
dtype: bool

In [7]:
df.isnull().sum()

Date    0
Open    0
dtype: int64

In [37]:
apple_processed = apple_complete.iloc[:,1:2].values

In [38]:
apple_processed

array([[19.779285],
       [19.567142],
       [19.1775  ],
       ...,
       [42.525002],
       [42.75    ],
       [42.630001]])

In [40]:
type(apple_complete)

pandas.core.frame.DataFrame

In [39]:
type(apple_processed)

numpy.ndarray

# Scaling

<img src = "https://chrisalbon.com/images/machine_learning_flashcards/MinMax_Scaling_print.png">

In [41]:
scaler = MinMaxScaler(feature_range=(0, 1))
apple_scaled = scaler.fit_transform(apple_processed)
apple_scaled

array([[0.19795893],
       [0.19086893],
       [0.17784675],
       ...,
       [0.95814044],
       [0.96566006],
       [0.96164959]])

In [43]:
apple_scaled.shape

(1259, 1)

# Make your Dataset

In [47]:
feature = []
labels = []
for i in range (60,1259):
    feature.append(apple_scaled[i-60:i,0])
    labels.append(apple_scaled[i,0])

In [50]:
len(feature)

1199

In [51]:
len(labels)

1199

In [55]:
feature[1]

array([0.19086893, 0.17784675, 0.15997852, 0.16858436, 0.16057529,
       0.1677966 , 0.15878493, 0.13691809, 0.13169017, 0.12732156,
       0.14602531, 0.13195272, 0.1391621 , 0.14423489, 0.08597521,
       0.07605636, 0.05951303, 0.08418478, 0.08239436, 0.08237053,
       0.08491289, 0.07870613, 0.06693724, 0.08176177, 0.0898544 ,
       0.10268564, 0.10566962, 0.10926236, 0.09458104, 0.09137027,
       0.09653854, 0.08728814, 0.08321795, 0.06926474, 0.07314397,
       0.07863455, 0.06666269, 0.07216517, 0.06693724, 0.05971593,
       0.04754118, 0.03999762, 0.05555025, 0.0436023 , 0.0499284 ,
       0.04986871, 0.0568513 , 0.04831704, 0.053545  , 0.05963238,
       0.06383385, 0.08537834, 0.08289574, 0.0743018 , 0.0795059 ,
       0.09157317, 0.09246834, 0.08174984, 0.07382435, 0.06437099])

In [68]:
labels[1]

0.047302486789651654

In [69]:
feature = np.array (feature)
labels = np.array (labels)

In [70]:
type(feature)

numpy.ndarray

In [71]:
type(labels)

numpy.ndarray

# Training your model

In [74]:
feature.shape[1]

60

In [75]:
feature = np.reshape(feature,(feature.shape[0],feature.shape[1],1))

In [76]:
feature.shape

(1199, 60, 1)